In [1]:
import pandas as pd

df_books = pd.read_csv("../../datasets/csv/books.csv")

<h1>
Select the title from the books table to view all book titles.
</h1>

In [2]:
display(df_books["title"])

0                          10-Day Green Smoothie Cleanse
1                                      11/22/63: A Novel
2                12 Rules for Life: An Antidote to Chaos
3                                 1984 (Signet Classics)
4      5,000 Awesome Facts (About Everything!) (Natio...
                             ...
345    Wild: From Lost to Found on the Pacific Crest ...
346    Winter of the World: Book Two of the Century T...
347    Women Food and God: An Unexpected Path to Almo...
348                                               Wonder
349         Wrecking Ball (Diary of a Wimpy Kid Book 14)
Name: title, Length: 350, dtype: str

<h1>
Select title and author from the books table.
</h1>

In [3]:
display(df_books[["title", "author"]])

,title,author
0,10-Day Green Smoothie Cleanse,JJ Smith
1,11/22/63: A Novel,Stephen King
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson
3,1984 (Signet Classics),George Orwell
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids
...,...,...
345,Wild: From Lost to Found on the Pacific Crest ...,Cheryl Strayed
346,Winter of the World: Book Two of the Century T...,Ken Follett
347,Women Food and God: An Unexpected Path to Almo...,Geneen Roth
348,Wonder,R. J. Palacio
349,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney

<h1>
Select all fields from the books table.
</h1>

In [4]:
display(df_books)

,id,title,author,year,genre
0,1,10-Day Green Smoothie Cleanse,JJ Smith,2016,Non Fiction
1,2,11/22/63: A Novel,Stephen King,2011,Fiction
2,3,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,2018,Non Fiction
3,4,1984 (Signet Classics),George Orwell,2017,Fiction
4,5,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,2019,Non Fiction
...,...,...,...,...,...
345,346,Wild: From Lost to Found on the Pacific Crest ...,Cheryl Strayed,2012,Non Fiction
346,347,Winter of the World: Book Two of the Century T...,Ken Follett,2012,Fiction
347,348,Women Food and God: An Unexpected Path to Almo...,Geneen Roth,2010,Non Fiction
348,349,Wonder,R. J. Palacio,2013,Fiction
349,350,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,2019,Fiction